---
title: "How Vogue is a Powerhouse in Advertising"
description: |
  Here is the final paper I wrote for my advertising class that examines Vogue's impact in advertising and the reasons for why it's my dream company to work for.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

As Miuccia Prada once said, "What you wear is how you present yourself to the world, especially today, when human contacts are so quick. Fashion is instant language." The fashion industry is considered one of the largest and most impactful industries in the world today. Almost everyone is a direct consumer of fashion, and the industry is one that contributes a lot to the global economy. Fashion helps people define themselves and has become a powerful tool of influence. However, the world of fashion would not be the way it is today without advertising. Advertising in the fashion industry is crucial if brands want to be recognized and it's the easiest way to communicate with consumers. As a result, it can be said that fashion and advertising go hand in hand. 

One of the most fascinating parts about fashion is that it attracts multiple types of consumers. There really isn't a specific mold that a person has to fit into. In my opinion, this is what makes the fashion industry so diverse and much more interesting. Regardless of whether you are interested in fashion or not, everyone wears clothes and is a direct consumer of the industry in some way. However, fashion is also extremely influential. Many fashion consumers are influenced by their peers' preferences and institutional power (Oran, 2019). Celebrities, role models, or even popular peer group members can become fashion leaders and influence the way people dress (2019). Many consumers view fashion as a status symbol and buy clothes that represent how they want others to perceive them. Others choose to shop at fast fashion stores and only care about getting the best deal. The customers in fashion vary, which is what makes the industry much more unique and exciting. 

There are many different types of fashion advertising. To begin with, print advertising and billboards were some of the original ways in which fashion was advertised. Magazines are a major sector for fashion advertising campaigns, especially for luxury brands (How Fashion Advertising Promotes Fashion Brands, 2014). When fashion campaigns are published in magazines such as Vogue or Bazaar, millions of people are exposed to it. The same goes for billboards. If a fashion campaign is put on a billboard in Times Square or 5th Avenue, it reaches a magnitude of people. Fashion ads also utilize TV commercials. Storytelling is extremely important in the commercial of a fashion campaign. This is because customers will likely buy a product if they feel emotionally connected to it in some way. Most of the time fashion brands are using commercials to advertise their entry-level products so they can target a wide range of audiences (2014). These ads will be seen by anyone who owns a TV, resulting in high exposure. Luxury brands will also use high profile individuals and celebrities to advertise their designs. For example, when a celebrity is photographed wearing a specific designer, a consumer will see the image and want to buy the same outfit for themself. This is why street style has become a prominent influence in fashion, and is another way that fashion advertising is able to target a potential consumer. 

In today's world, digital advertising has become the main way to advertise and this applies to the fashion industry as well. Many brands are taking advantage of social media platforms and using them to advertise their products. Technology has encouraged people to interact with brands and has changed the way of communication between the brand and consumer (How Fashion Advertising Promotes Fashion Brands, 2014). According to The Wall Street Journal, "Fashion houses such as Louis Vuitton and Gucci are shifting marketing dollars from print ads to digital channels such as social media and online advertising" (Kirkpatrick, 2017). François-Henri Pinault, chief executive of Kering, told the Wall Street Journal he estimates the company spends up to 40% of its communication budget on digital because that's where the consumer is (LaRose, 2017). As a result of social media, fashion bloggers and influencers have been able to become advertisements themselves. They are directly promoting the brand by wearing its clothes. Companies now send digital influencers PR packages in hopes that they will be photographed in the clothing. In fact, many luxury fashion brands are sending influencers to Fashion Week and having them sit front row at their shows in exchange for them posting content on their social media pages. Fast fashion brands are also capitalizing on influencer advertising. H&M launched a social media influencer program with 22 social media personalities serving as ambassadors. These influencers will be delivering content directly to consumers through their own Instagram accounts during the yearlong partnership (Edelson, 4). Clearly, influencer advertising has proven to be an effective new way for fashion brands to advertise their products. 

Depending on the brand and its values, fashion ads hold different messages. Recently, a lot of fashion ads have messages relating to sustainability and body acceptance. However this has not always been the case. In the past, many fashion ads objectified women and utilized the message of "sex sells". For example, Calvin Klein published an ad in 1992 that featured a young Kate Moss and Mark Wahlberg. In the ad, 17 year old Moss was topless and at one point Wahlberg points to her and says "Now that could definitely come between me and my Calvins." Even by today's standards, the ad is considered provocative and unapologetically sexual. Not only that, but Moss was seen as an unrealistic and unattainable role model for the young women the commercial was targeting mainly due to her "underfed" frame and "heroin chic" appearance (Phelps, 2017). Thankfully, fashion ads today seem to have stepped away from their old ways and are making the effort to put out ads that neither objectify women or depict unrealistic standards of beauty. 

If I were to choose a dream company to work for, it would be Vogue. Not only is Vogue the most famous and recognized fashion and lifestyle magazine in the world, but it is universally known as fashion's bible. The magazine was founded in 1892 and was a weekly periodical that was subscribed to by New York's elite (Borrelli, n.d). Condé Nast then bought the company in 1909 and began to transform it into the fashion powerhouse it is today (n.d). Nast insisted that the covers were done by the best photographers and illustrators in the industry. As a result, each Vogue cover became a representation of the movements in each decade. Vogue today is not only extremely influential, but is edited by the most powerful woman currently in the fashion industry, Anna Wintour (Tangdall, 2017). As a result, Vogue claims to be a magazine that empowers women through its strong female editors, writers, designers, and models (2017). 

Vogue is my dream company for many reasons. To begin with, there is a certain level of prestige you carry if you land a job with Vogue and it is a dream company for most fashion lovers. Vogue was also the first magazine I grew up reading and it introduced me to the fashion world. Growing up, I would always look forward to receiving my new issue of Vogue and it was where I went to get any sort of inspiration. Ideally, I want to work for a company that will challenge me creatively and won't necessarily be a traditional desk job. Simply from doing research about the company, I know that Vogue is a place where no day is the same. I want a job that isn't repetitive and where the company atmosphere is engaging. The people who work at Vogue all have a similar level of work ethic or else they wouldn't have been hired. It is a company that truly has so many different elements to it, and this is something that attracts me. Finally, a dream of mine has always been to attend Fashion Week and there are only a limited number of companies that could potentially make this happen for me. Fashion month is considered to be the most important time of the year in fashion and if you work for a big fashion brand or magazine, odds are you will be involved in it. Being able to attend Fashion Week being associated with a company like Vogue would be surreal and is a goal that I hope to achieve in the future.

Vogue is extremely selective about the advertisements they choose to display in their magazines. In fact, British Vogue has said that "Vogue's ads are as important as the content" (Southern, 2015). The ads in Vogue are considered premium, and readers tend to value them as much as they would the content (2015). According to Vogue's associate publisher Sallie Berkerey, their ads are described as "genuine," "trusted" and "appealing" (2015). Many of the ads in Vogue are by prestigious, luxury brands who are using the magazine to support their ad campaigns. Vogue's advertising is mainly targeted to those with a high-income. Their advertisements tend to be relevant and valued, and many readers take action as a result of seeing advertising in Vogue (Advertising in Vogue, n.d). Additionally, Vogue has really made an effort to transition into the digital advertising space and release all of their magazines digitally in addition to print. In fact, Vogue was the first brand to pioneer new standout video content in June 2015, with the launch of Vogue Video (Geary, 2015). This proved to be an absolute success and many of their competitors ended up implementing the same strategy. Vogue's video content receives millions of views and this number is only increasing as they continue to adapt digitally. The brand has proven that they know how to successfully complement print and digital, and they always aim to produce something unique. Somehow, they continue to have high success rates for both digital and print, which is incredibly rare in this new digital age. This is what makes Vogue stand out from their competitors. 

In 2019, Vogue announced the launch of 'Vogue Values', which is a global mission statement adopted by all 26 editions of the magazine and articulates the shared commitments for 2020 and beyond ("Vogue Values", 2019). Each editor in chief of Vogue signed their name to this statement and it's a testament to the power of the global brand when it speaks with a collective voice (2019). The last sentence in the statement reads, "We speak with a unified voice across 26 editions standing for the values of diversity, responsibility and respect for individuals, communities and for our natural environment" (2019). This campaign is just one way Vogue continues to attract more readers, build loyalty, and make themselves more attractive than their competitors. Vogue believes that their readers expect them to be socially responsible, represent people from all backgrounds, and have a strong voice on current affairs and global issues (Vogue Announces Vogue Values, 2019). Roger Lynch, the CEO of Condé Nast says, "Vogue has the ability to move, influence and inspire --- and with that, a responsibility to lead on the issues that matter most" (2019). As the world's leading fashion title, Vogue knows how to keep their audience happy and is an example of a company that listens to what their readers want. The advertising they choose to display in each issue represents not only the luxury element of the brand, but also the ethics. Vogue is consistent and as a result, readers are able to connect with them. 

There are so many different ways to advertise Vogue, but I believe that social media is the best method, as it has already proven to be extremely successful. Youtube, Instagram, and Facebook would be the three main platforms I would focus advertising on. Facebook would target the middle to older aged readers, since it's the platform that older generations seem to prefer. Instagram and Youtube would mainly advertise to the millenial and Gen Z audience. It's also important for Vogue ads to depict the magazine's beliefs. For instance if I were to come up with an ad focusing on Vogue's sustainability efforts, the ad would show an illustrated image of a girl holding a pile of used Vogue issues in her hands deciding whether to toss them in the garbage right in front of her or walk the extra mile and put them in the donation/recycling bin. The headline would say "Waste it or preserve it. The choice is yours. Go Green with Vogue." It's important that the ad is illustrated because it will reduce the environmental impact of photoshoots, making the ad even more powerful. This ad could be a part of Vogue's sustainability campaign and would be shown across all of their platforms. It could even be made into a video series and use emotion to draw people in. If the ad campaign is successful, there will be increased word of mouth resulting in more reach. It's important for Vogue advertisements to connect with readers and remind them of why they choose to read Vogue over anyone else.

Overall, the fashion industry is evolving and its ads are reflective of this. Vogue is a company that is adapting to change, which is how it is able to stay successful while many of its competitors are struggling. Vogue continues to remain a top name in fashion, and its values are reflective of those I want my future employer to have. It would be an absolute dream to work for a company like Vogue and be a part of their social media or digital advertising team. I hope to gain more experience in the fashion industry post graduation and work hard to be able to have the credentials to apply for a job at Vogue in the future. It's important to take things one step at a time in any career and that is exactly what I plan to do. Move over Anna Wintour, here I come. 

#####  [References]{.ul}

###### Advertising in Vogue Magazine -- The Media Ant. (n.d.). Retrieved from <https://www.themediaant.com/magazine/vogue-magazine-advertising>

###### Borrelli, L. (n.d.). Vogue. Retrieved from <https://fashion-history.lovetoknow.com/fashion-clothing-industry/vogue>

###### Edelson, S. (2019). H&M's Power Play: The fast-fashion retailer looks to leverage Internet personalities and their fans. WWD: Women's Wear Daily, 4.

###### Emma Geary (British Vogue): "The print and digital propositions are entirely complementary" - Leaders League. (2015, May 26). Retrieved from <https://www.leadersleague.com/en/news/emma-geary-british-vogue-the-print-and-digital-propositions-are-entirely-complementary>

###### How Fashion Advertising Promotes Fashion Brands. (2014, October 9). Retrieved from <http://fashionchinaagency.com/fashion-advertising-promotes-fashion-brands/>

###### Kirkpatrick, D. (2017, June 12). Fashion brands are increasing digital spending. Retrieved from <https://www.marketingdive.com/news/fashion-brands-are-increasing-digital-spending/444748/>

###### LaRose, D. (2017, August 9). The Digital Age: Fashion Ads Moving Off Print And Online. Retrieved from <https://www.carmenbusquets.com/journal/post/the-digital-age-fashion-ads-moving-off-print-and-online>

###### Oran, A. F. (2019). Fashion's Effect on Consumer's Preference Formation. Journal of Economic Issues (Taylor & Francis Ltd), 53(4), 1088--1102. <https://doi-org.libezproxy2.syr.edu/10.1080/00213624.2019.1668340>

###### Phelps, N. (2017, February 1). Sex Sells: Calvin Klein's 1990s Ads Stirred Libidos and Controversies in Equal Measure. Retrieved from <https://www.vogue.com/article/calvin-klein-jeans-90s-ads-kate-moss-mark-wahlberg-controversy>

###### Southern, L. (2015, September 28). The British Vogue guide to making people pay attention to ads. Retrieved from <https://digiday.com/uk/british-vogue-attention-ads/>

###### Tangdall, S. (2017). The Influence of Popular Culture on Women's Identities: A Diachronic Discourse Analysis of Vogue Magazine. Southern Journal of Linguistics, 41(2), 47--94.

###### Vogue announces Vogue Values. (2019, December 4). Retrieved from <https://www.condenast.com/news/vogue-values-launch>

###### Vogue Values: All 26 Editions of Vogue Come Together to Announce a Global Mission Statement. (2019, December 6). Retrieved from <https://en.vogue.me/culture/vogue-values/>

######  
