---
title: "Children Are What They Eat"
description: |
  Here is a feature story I wrote about how childhood nutrition can affect adult life.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Maria Miller wished she had thought twice before giving her daughter Natalie that McDonald's Happy Meal. 

Natalie is now 27 years old and has suffered from high cholesterol and high blood pressure for at least a decade. Miller believes that this is linked to her poor diet during pregnancy and the meals she fed Natalie as a child. 

"I was a single mom who was still working a full time job and never had time to properly cook meals at home," Miller recalled. "I had a child to feed and the easiest thing to do was order cheap takeout throughout the week. In the moment I wasn't thinking about the long term effects that decision could have in the future."  

More research has come out about the impact childhood diet may have on adult life. Scientists have not only found links between childhood diet and metabolic diseases such as obesity, but also with mood disorders such as anxiety and depression. 

A recent 2021[ study](https://news.ucr.edu/articles/2021/04/07/childhood-diet-and-exercise-creates-healthier-less-anxious-adults) conducted by researchers at the University of California, Riverside found that exercise and a healthy diet during childhood may lead to adults with bigger brains and lower levels of anxiety. 

Marcell Cadney, a physiology doctoral student at UCR, led the study and used mice to obtain these findings. The mice were split into four groups- those with access to exercise, those without access, those fed a standard, healthy diet and those fed a Western diet, which consisted of foods that were high in fat and sugar. 

"There are various aspects about our health that we'd like to understand and many of those aspects are undoubtedly driven by genetics," Cadney said. "However another factor that might be important is our early life experiences. I personally wanted to know what sort of factors mice experience early in life that could have long lasting effects into adulthood."

Cadney and his team discovered that the mice that had access to exercise and were fed a standard, healthy diet exhibited less anxiety like behaviors. On the contrary, the mice that were exposed to a Western diet since early life had an increased adult preference for foods high in fat, salt, and sugar. These findings can help explain the importance of exposure for healthy eating during childhood.  

Alison Ventura, an associate professor at California Polytechnic State University whose research focuses on obesity prevention during early childhood, believes that parents are the ones who ultimately shape the types of foods their children are craving. 

"Children are very plastic, meaning that they change and learn so quickly, which helps them grow and develop," Ventura said. "But this also means that there's so much potential to shape healthy habits and preferences. The more that we can do during early childhood, then the easier that child will have as an adult in terms of being able to maintain a healthy body weight and practice healthy habits that will support their health throughout adulthood."

This is what Miller considers to be her biggest failure as a parent. Since she had exposed Natalie to the Western diet at such an early age, high sodium and fatty foods seemed to be all she craved. 

"I honestly didn't want to deal with the temper tantrums," Miller admitted. "As a single mom, I was exhausted and already felt a tremendous amount of guilt. I took the easy route which was to just give her what she wanted. Unfortunately, what she wanted were foods high in fat and sugar." 

Similar to the mice, Natalie developed a preference for foods commonly associated with the Western diet. However according to Ventura, these preferences can be formed as early as pregnancy. This is because both amniotic fluid and breast milk contain molecules derived from the mother's diet which are passed down to the fetus. 

"We know that prenatally the mom's nutrition is really important because her diet can get transmitted to the fetus," Ventura mentioned. "For example if the mom has a garlicky meal, that garlic flavor is going to be transmitted into the amniotic fluid, and then that little fetus is going to be bathed in garlic flavor. If that happens repeatedly then the fetus is going to learn to love garlic, and when that fetus becomes a child it's going to recognize the flavor. The bottom line is that the mom's diet is really critical for establishing this foundation of health for the baby, especially during the prenatal period." 

This is why women's health and diet during pregnancy should not be ignored and is a topic that is severely lacking in discussion. Most women with unexpected pregnancies like Tsutsumi don't realize the importance of nutrition during pregnancy. Oftentimes, the bad eating habits that are formed during pregnancy will stay consistent even after the child is born. 

"My diet during pregnancy was the exact opposite of healthy," Miller recalled. "Not only was I eating fast food pretty much every day, but I was also consuming giant portions of it. I let myself eat whatever I wanted because I thought that was normal for pregnant women to do. I wish I hadn't been so naive." 

Daniel Hoffman, a professor in the department of nutritional sciences at Rutgers University, is worried about the way the new generation of parents will feed their children. He believes that the best thing parents can do is introduce their children to a variety of healthy foods from a young age without making a big deal about it. 

"When I was younger, I either ate what my mother made or I didn't eat," Hoffman said. "Nowadays, you'll see kids refuse certain foods and what do parents do? They'll give them something else. Behaviorally, they're training children that if they say no they'll get something else. But nationally, what's happening is that parents usually end up giving their kids something sweet or salty instead." 

Hoffman encourages parents to think about the negative consequences that can occur from allowing children to refuse a meal and consume an unhealthy alternative instead. In fact, he believes that it is sometimes better for children to skip a meal rather than giving them the unhealthy food they really wanted, because this will have less of a long term impact on their health.

"No child has died from skipping dinner," Hoffman reiterated. "But the child may die later on from heart disease because the parents manipulated their preference for these less desirable foods. So the best advice I give to parents is to have healthy foods in the house, prepare healthy meals, and don't offer alternatives."

In Miller's case, she worries that the health problems Natalie has faced are irreversible. However, researchers like Cadney strongly believe that it's never too late to start working on your health. 

"What we learned from the mice is that regardless of their early life experiences, they all lost significant amounts of body fat after having two weeks of exercise," Cadney said. "So that should tell you that regardless of what your genetics and life experiences were, you can start taking care of yourself today and that will have a significant effect on the risk factors of  cardiovascular disease, obesity, type two diabetes and so on."

Cadney also worries about the children who are currently living through the COVID-19 pandemic and the future health implications they may face because of it. 

"Unfortunately in a couple decades we might see a sudden spike in obesity rates, in type two diabetes, and so on just because of these early life experiences children faced due to COVID," Cadney mentioned. "Parents need to understand that their kids do need a consistent diet of healthy foods that they might have been getting at school, as well as time for recess. We need to have action plans of what to do with kids specifically, so that we avoid the trap that is set by these early life experiences following us into adulthood."

Luckily, Miller did not make the same mistakes during her second pregnancy and had a lot more help the next time around. Her son Ryan has grown up with a balanced diet and does not appear to have any underlying metabolic conditions like Natalie. The main message that Tsutsumi wants to get across to new parents is to not make the same mistakes she did. 

"Nobody really thinks about how the foods you eat from a young age may affect your long term health as an adult," Miller said. "My daughter has luckily been able to get her health under control but she will always have to be careful about what she eats. As a parent, it's not a fun feeling watching your child suffer and knowing that you may have contributed to it. I just want future moms to be more mindful of their nutrition during pregnancy and what they choose to feed their children throughout childhood."

\
\
\
