---
title: "A Visual Analysis of Harrods Department Store"
description: |
  Here is a visual analysis paper I wrote for a fashion marketing class I took when I studied abroad in London. 
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Harrods is universally recognized as one of the most famous department stores in the world. It is considered to be one of the most glamorous shopping experiences in London, resulting in it becoming somewhat of a tourist attraction itself. In fact, Harrods has been named the world's best performing luxury department store (IDEX Magazine, 2019). With 7 floors and 330 departments, Harrods is a shopping lover's dream. All of the elements that make up Harrods is reflective of the prestige it carries and its interior truly reveals the brand's identity. 

Ever since Harrods opened, its motto has been 'Omnia Omnibus Ubique'. This is a Latin phrase, which means "All things, for all people, everywhere" (History of Harrods department store, 2010). This motto is incredibly fitting because throughout the store's entire history, it has sold a wide assortment of goods. It started out as a small grocery store in 1849, and then expanded rapidly because of its success (2010). By the 1950s, it had become society's favorite store not only in London, but worldwide. Harrods has always been known for its service and the huge range of merchandise it carries from all over the world. The Harrods building that is present today was built in 1905 and has 330 departments, 20 restaurants, a food hall, a bank, a hair and beauty salon, and much more (Store Guide - Harrods, n.d.). The store still sells gourmet grocery items, however its emphasis is now placed on luxury clothing. When customers enter Harrods, they enter a different world where every experience is truly unique. 

The interior of Harrods is unlike any other department store. The architecture and interior design are what initially attract the most attention when walking in. At the door, Harrods customers are immediately greeted by a doorman dressed in a sharp green and gold uniform. These are the iconic colors that customers associate the Harrods brand with. Inside the building, there are gold accents everywhere and it truly feels as though a person has entered an opulent kingdom. To put it simply, the inside of Harrods is spectacular. The store has a Renaissance-style interior, with the ceilings and frescos being painted and modeled by French artists in the Renaissance style (Orr, 2019). Giant columns take up various parts of the building and there are Egyptian accents everywhere. This is because Harrods used to be owned by Al Fayed, an Egyptian businessman who incorporated many Egyptian elements into the design of the store (History of Harrods department store, 2010). The bronze Eqyptian escalators also make up a key sculptural element in the building. The food hall is lavishly decorated with beautiful tiles and has hundreds of delicious gourmet food options. Each floor in Harrods has its own theme and customers can spend hours exploring the entirety of the store. The dim lighting present throughout the store gives the clothes a more intimate and high-end feel. The music plays softly in the background and creates the perfect ambiance for shoppers to explore and walk around in. There is an elegance to Harrods and it's clear that the atmosphere caters to specific individuals, preferably those with money. Each department in Harrods can be seen as a showcase for luxury goods. It is not a place where children are seen running around aimlessly. The interior is truly timeless and reflects the level of prestige and high status the store holds. 

The Harrods customer can be divided into two categories: the rich and the tourists. It is apparent that the store is targeted to the upper class, and this is clearly the market segment that management focuses the most on. The visitors at Harrods may be of all different age groups, however most of the shoppers belong to a higher class and expect the service and appearance of the store to reflect that. The book Consumerism: As a Way of Life states that "Fashion not only identifies the individual as being a member of a particular class, but also highlights that he or she is not a member of an alternative group" (Miles, 1998). This is extremely true for Harrods customers. By routinely shopping at Harrods, individuals are placing themselves in a particular social class whether they are intending to or not. A person who shops at Harrods is giving off the impression that they are of a higher status than most. This means that the experience of shopping at Harrods is expected to be top notch. The rich expect their shopping experiences to be at the highest level possible and Harrods needs to achieve this by both looking and acting the part. The Harrods Fine Jewelry room is a great example of a department that completely fits in with the brand narrative. The room has an enhanced private environment where customers can expect an entirely personalized shopping experience. The design of the space was inspired by Harrods' archives and set out to recreate the historical ambiance of its jewelry department (Oliveira, 2016). The room has antique detailing, a gentle onyx color palette and polished brass, giving the space an elegant feel (2016). The room also includes bespoke lighting which is used to display jeweler's collections in their most sparkling light (2016). Each brand has a dedicated space with a unique and breathtaking interior design. For instance, the Graff Diamonds boutique in Harrods has a striking gold exterior that is complemented by striped marble floors and decadent wall panels (The Jewelry Editor, 2014). Similarly, the Cartier boutique is lavished with handcrafted decorative walls, complemented by glass and bronze furnishings (Mann, 2017). It is safe to say that there are only a select number of people who are going to be walking through the jewelry department with intentions of actually purchasing something. The appearance of the jewelry department in Harrods needs to display pure wealth and elegance, or else customers will choose to purchase their jewelry elsewhere. To put it simply, if a person is willing to pay for fine jewelry, they will most likely choose to purchase the item at the place that fits in most with their identified class. The jewelry room in Harrods clearly represents the type of clientele the store is selling to.  

Another popular part of Harrods is the Super Brands department. Situated on the first and second floor of the building, this department features some of the biggest designers in the fashion industry. The two floors include top brands such as Prada, Chanel, Dior, and Alexander McQueen. The first floor is filled with women ready to wear, while the second floor is meant for men. Marble, black granite, bronze and brass are present throughout both floors, and each brand has its own space in an intimate setting. The layout of the department creates a 'boutique-within-a-boutique' effect that caters to Harrods' luxury clientele (Harrods Superbrands, n.d.). The lighting is intentionally low to create more of an ambiance and set the tone of the department. Both floors are filled with personal shoppers who are designated to specific brands. There aren't as many kids and random tourists browsing through these two floors. The Super Brands department truly reinforces Harrods' status as the world's premier high fashion retailer. 

The customers who browse through Harrods also stand out. When walking around the store, it becomes apparent that nobody is dressed inappropriately. This is because Harrods introduced a dress code policy in 1989 that still applies today. The clothes people wear send a message, and Harrods does not want its brand to be associated with the wrong image. The book, The Fashioned Body: Fashion, Dress and Modern Social Theory, says that "Fashion and dress have a complex relationship to identity: on the one hand the clothes we choose to wear can be expressive... telling others something about our gender, class, status and so on; on the other our clothes cannot always be read, since they do not speak and can therefore be open to misinterpretation" (Entwistle, 2000). To avoid this misinterpretation, Harrods has the right to deny entry to anyone wearing attire that they consider to be inappropriate. Proper attire, including tops and shirts, must be worn at all times and visible tattoos and clothing that contain objectionable language or designs are not permitted. This is a way to filter out the customers who do not look like they belong in a place like Harrods. The department store is making it extremely clear that they are not in the same category as Primark. Even though they have adapted their dress code to modern times, Harrods still has a reputation to uphold and they try to manage this by having somewhat of a say in who walks into their store. 

To conclude, Harrods is famous for its high quality image and the atmosphere that comes along with it. The glamorous interior of the store reflects the nature of the brand and depicts the type of customer Harrods is selling to. Harrods is the perfect example of a department store that is unapologetically meant for the upper class and isn't afraid to make that known. Top level customers are given the most excellent service and the most amazing product, in the best possible environment. Harrods is truly a symbol of social class, making it no surprise that it is the most famous luxury department store in the world. 

##### [References]{.ul}

###### Entwistle, J. (2000). The fashioned body: Fashion, dress, and modern social theory. Cambridge: Polity Press.

###### Harrods Named the World's Best-Performing Luxury Department Store. (2019). IDEX Magazine, 30(350), 43

###### Harrods Superbrands. (n.d.). Retrieved from <https://www.makearchitects.com/projects/harrods-superbrands/>

###### History of Harrods department store. (2010, May 8). Retrieved from <https://www.bbc.com/news/10103783>

###### Mann, M. (2017, December 14). Inside the New Cartier Boutique at Harrods, Knightsbridg: 

###### Watches: Watches & Jewellery. Retrieved from <https://luxurylondon.co.uk/watches-and-jewellery/watches/new-cartier-boutique-at-harrods-fine-jewellery-room>

###### Miles, S. (1998). Consuming fashion. In Consumerism: As a way of life (pp. 90-106). London: SAGE Publications Ltd doi: 10.4135/9781446217115.n6

###### Oliveira, F. (2016, August 10). Harrods Redesigned its Fine Jewelry Room. Retrieved from <https://www.designlimitededition.com/harrods-redesigned-fine-jewelry-room/>

###### Orr, E. M. (2019). Designing the department store: display and retail at the turn of the twentieth century. London: Bloomsbury Publishing.

###### Store Guide - Harrods. (n.d.). Retrieved from <https://www.harrods.com/en-gb/store-guide> 

###### The Jewelry Editor. (2014, March 11). The opening of a new Graff Diamonds boutique 

###### completes the line up at the revamped Fine Jewellery Room at Harrods. Retrieved from <http://www.thejewelleryeditor.com/jewellery/article/the-opening-of-a-new-graff-diamonds-boutique-completes-the-line-up-at-the-revamped-fine-jewellery-room-at-harrods/>

######   
